DROP TABLE IF EXISTS beers, trees, biscuits, noodles;


CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  abv TEXT NOT NULL,
  color TEXT
);

CREATE TABLE trees (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  age TEXT NOT NULL
);

CREATE TABLE biscuits (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  flour TEXT NOT NULL,
  sauce TEXT NOT NULL
);

CREATE TABLE noodles (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  region TEXT NOT NULL
);
